// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: fasten.proto

package service

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// One of the two possible payloads
type FastenReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackageMetadata *FastenReport_PackageMetadata `protobuf:"bytes,1,opt,name=package_metadata,json=packageMetadata,proto3" json:"package_metadata,omitempty"`
	FileMetadata    []*FastenReport_FileMetadata  `protobuf:"bytes,2,rep,name=file_metadata,json=fileMetadata,proto3" json:"file_metadata,omitempty"`
}

func (x *FastenReport) Reset() {
	*x = FastenReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fasten_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FastenReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastenReport) ProtoMessage() {}

func (x *FastenReport) ProtoReflect() protoreflect.Message {
	mi := &file_fasten_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastenReport.ProtoReflect.Descriptor instead.
func (*FastenReport) Descriptor() ([]byte, []int) {
	return file_fasten_proto_rawDescGZIP(), []int{0}
}

func (x *FastenReport) GetPackageMetadata() *FastenReport_PackageMetadata {
	if x != nil {
		return x.PackageMetadata
	}
	return nil
}

func (x *FastenReport) GetFileMetadata() []*FastenReport_FileMetadata {
	if x != nil {
		return x.FileMetadata
	}
	return nil
}

// One of the two possible payloads
type FastenError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message    string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Stacktrace []string `protobuf:"bytes,3,rep,name=stacktrace,proto3" json:"stacktrace,omitempty"`
}

func (x *FastenError) Reset() {
	*x = FastenError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fasten_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FastenError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastenError) ProtoMessage() {}

func (x *FastenError) ProtoReflect() protoreflect.Message {
	mi := &file_fasten_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastenError.ProtoReflect.Descriptor instead.
func (*FastenError) Descriptor() ([]byte, []int) {
	return file_fasten_proto_rawDescGZIP(), []int{1}
}

func (x *FastenError) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FastenError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FastenError) GetStacktrace() []string {
	if x != nil {
		return x.Stacktrace
	}
	return nil
}

// Final response object
type FastenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginName    string                      `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	PluginVersion string                      `protobuf:"bytes,2,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	Input         *FastenResponse_FastenInput `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	CreatedAt     *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Types that are assignable to Payload:
	//	*FastenResponse_Report
	//	*FastenResponse_Error
	Payload isFastenResponse_Payload `protobuf_oneof:"payload"`
}

func (x *FastenResponse) Reset() {
	*x = FastenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fasten_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FastenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastenResponse) ProtoMessage() {}

func (x *FastenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fasten_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastenResponse.ProtoReflect.Descriptor instead.
func (*FastenResponse) Descriptor() ([]byte, []int) {
	return file_fasten_proto_rawDescGZIP(), []int{2}
}

func (x *FastenResponse) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *FastenResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *FastenResponse) GetInput() *FastenResponse_FastenInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *FastenResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (m *FastenResponse) GetPayload() isFastenResponse_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *FastenResponse) GetReport() *FastenReport {
	if x, ok := x.GetPayload().(*FastenResponse_Report); ok {
		return x.Report
	}
	return nil
}

func (x *FastenResponse) GetError() *FastenError {
	if x, ok := x.GetPayload().(*FastenResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isFastenResponse_Payload interface {
	isFastenResponse_Payload()
}

type FastenResponse_Report struct {
	Report *FastenReport `protobuf:"bytes,5,opt,name=report,proto3,oneof"`
}

type FastenResponse_Error struct {
	Error *FastenError `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*FastenResponse_Report) isFastenResponse_Payload() {}

func (*FastenResponse_Error) isFastenResponse_Payload() {}

type FastenReport_PackageMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Licenses []string `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses,omitempty"`
	Authors  []string `protobuf:"bytes,2,rep,name=authors,proto3" json:"authors,omitempty"`
}

func (x *FastenReport_PackageMetadata) Reset() {
	*x = FastenReport_PackageMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fasten_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FastenReport_PackageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastenReport_PackageMetadata) ProtoMessage() {}

func (x *FastenReport_PackageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fasten_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastenReport_PackageMetadata.ProtoReflect.Descriptor instead.
func (*FastenReport_PackageMetadata) Descriptor() ([]byte, []int) {
	return file_fasten_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FastenReport_PackageMetadata) GetLicenses() []string {
	if x != nil {
		return x.Licenses
	}
	return nil
}

func (x *FastenReport_PackageMetadata) GetAuthors() []string {
	if x != nil {
		return x.Authors
	}
	return nil
}

type FastenReport_FileMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string   `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Sha_1    string   `protobuf:"bytes,2,opt,name=sha_1,json=sha1,proto3" json:"sha_1,omitempty"`
	Licenses []string `protobuf:"bytes,3,rep,name=licenses,proto3" json:"licenses,omitempty"`
}

func (x *FastenReport_FileMetadata) Reset() {
	*x = FastenReport_FileMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fasten_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FastenReport_FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastenReport_FileMetadata) ProtoMessage() {}

func (x *FastenReport_FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_fasten_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastenReport_FileMetadata.ProtoReflect.Descriptor instead.
func (*FastenReport_FileMetadata) Descriptor() ([]byte, []int) {
	return file_fasten_proto_rawDescGZIP(), []int{0, 1}
}

func (x *FastenReport_FileMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *FastenReport_FileMetadata) GetSha_1() string {
	if x != nil {
		return x.Sha_1
	}
	return ""
}

func (x *FastenReport_FileMetadata) GetLicenses() []string {
	if x != nil {
		return x.Licenses
	}
	return nil
}

type FastenResponse_FastenInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Product string `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Forge   string `protobuf:"bytes,2,opt,name=forge,proto3" json:"forge,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *FastenResponse_FastenInput) Reset() {
	*x = FastenResponse_FastenInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fasten_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FastenResponse_FastenInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FastenResponse_FastenInput) ProtoMessage() {}

func (x *FastenResponse_FastenInput) ProtoReflect() protoreflect.Message {
	mi := &file_fasten_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FastenResponse_FastenInput.ProtoReflect.Descriptor instead.
func (*FastenResponse_FastenInput) Descriptor() ([]byte, []int) {
	return file_fasten_proto_rawDescGZIP(), []int{2, 0}
}

func (x *FastenResponse_FastenInput) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *FastenResponse_FastenInput) GetForge() string {
	if x != nil {
		return x.Forge
	}
	return ""
}

func (x *FastenResponse_FastenInput) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_fasten_proto protoreflect.FileDescriptor

var file_fasten_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x61, 0x73, 0x74, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd0, 0x02, 0x0a, 0x0c, 0x46, 0x61, 0x73,
	0x74, 0x65, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x50, 0x0a, 0x10, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x61,
	0x73, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x47, 0x0a, 0x0d, 0x66,
	0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x61, 0x73,
	0x74, 0x65, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x47, 0x0a, 0x0f, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x63, 0x65, 0x6e,
	0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x69, 0x63, 0x65, 0x6e,
	0x73, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x73, 0x1a, 0x5c, 0x0a,
	0x0c, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a,
	0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x68,
	0x61, 0x5f, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x68, 0x61, 0x31, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x5b, 0x0a, 0x0b, 0x46,
	0x61, 0x73, 0x74, 0x65, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x63,
	0x6b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x22, 0x91, 0x03, 0x0a, 0x0e, 0x46, 0x61, 0x73,
	0x74, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x61, 0x73,
	0x74, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x61, 0x73, 0x74,
	0x65, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x39,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2f, 0x0a, 0x06, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x46, 0x61, 0x73, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x2c, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x46, 0x61, 0x73, 0x74, 0x65, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x57, 0x0a, 0x0b, 0x46, 0x61, 0x73, 0x74,
	0x65, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x66, 0x6f, 0x72, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x18, 0x0a, 0x16,
	0x6f, 0x72, 0x67, 0x2e, 0x71, 0x6d, 0x73, 0x74, 0x72, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fasten_proto_rawDescOnce sync.Once
	file_fasten_proto_rawDescData = file_fasten_proto_rawDesc
)

func file_fasten_proto_rawDescGZIP() []byte {
	file_fasten_proto_rawDescOnce.Do(func() {
		file_fasten_proto_rawDescData = protoimpl.X.CompressGZIP(file_fasten_proto_rawDescData)
	})
	return file_fasten_proto_rawDescData
}

var file_fasten_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fasten_proto_goTypes = []interface{}{
	(*FastenReport)(nil),                 // 0: service.FastenReport
	(*FastenError)(nil),                  // 1: service.FastenError
	(*FastenResponse)(nil),               // 2: service.FastenResponse
	(*FastenReport_PackageMetadata)(nil), // 3: service.FastenReport.PackageMetadata
	(*FastenReport_FileMetadata)(nil),    // 4: service.FastenReport.FileMetadata
	(*FastenResponse_FastenInput)(nil),   // 5: service.FastenResponse.FastenInput
	(*timestamppb.Timestamp)(nil),        // 6: google.protobuf.Timestamp
}
var file_fasten_proto_depIdxs = []int32{
	3, // 0: service.FastenReport.package_metadata:type_name -> service.FastenReport.PackageMetadata
	4, // 1: service.FastenReport.file_metadata:type_name -> service.FastenReport.FileMetadata
	5, // 2: service.FastenResponse.input:type_name -> service.FastenResponse.FastenInput
	6, // 3: service.FastenResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 4: service.FastenResponse.report:type_name -> service.FastenReport
	1, // 5: service.FastenResponse.error:type_name -> service.FastenError
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_fasten_proto_init() }
func file_fasten_proto_init() {
	if File_fasten_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fasten_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FastenReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fasten_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FastenError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fasten_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FastenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fasten_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FastenReport_PackageMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fasten_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FastenReport_FileMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fasten_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FastenResponse_FastenInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_fasten_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*FastenResponse_Report)(nil),
		(*FastenResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fasten_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fasten_proto_goTypes,
		DependencyIndexes: file_fasten_proto_depIdxs,
		MessageInfos:      file_fasten_proto_msgTypes,
	}.Build()
	File_fasten_proto = out.File
	file_fasten_proto_rawDesc = nil
	file_fasten_proto_goTypes = nil
	file_fasten_proto_depIdxs = nil
}
